# Generated by Django 5.2.7 on 2025-10-24 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='bot_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scenario',
            name='scenario_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='step',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='step_type',
            field=models.CharField(choices=[('user_input', 'Ввод пользователя'), ('bot_response', 'Ответ бота')], default='bot_response', max_length=20),
        ),
    ]
