# Generated by Django 5.2.7 on 2025-11-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bot_bot_config_scenario_scenario_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
